spring:
  application:
    name: spring-cloud-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Nodo-IT/spring-cloud-example-config # required
          default-label: main # required

server:
  port: 8888
